# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."musikat" = {
    image = "localhost/compose2nix/musikat:latest";
    environment = {
      "API_HOST" = "0.0.0.0";
      "API_PORT" = "8000";
      "AUDIO_QUALITY" = "128";
      "CORS_ORIGINS" = "http://localhost:3000,http://127.0.0.1:3000";
      "DEFAULT_METADATA_PROVIDER" = "deezer";
      "DOWNLOAD_DIR" = "./downloads";
      "NAVIDROME_API_URL" = "http://host.docker.internal:4533";
      "NAVIDROME_MUSIC_PATH" = "/music";
      "NAVIDROME_PASSWORD" = "ZnHN^3b6lSX6O1";
      "NAVIDROME_USERNAME" = "nyx";
      "OUTPUT_FORMAT" = "mp3";
    };
    volumes = [
      "/home/nyx/Downloads:/app/downloads:rw"
      "/var/Music:/music:rw"
    ];
    ports = [
      "8081:8000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=musikat"
      "--network=musikat_music-network"

      "--userns=keep-id:uid=991,gid=991"
    ];
  };
  systemd.services."podman-musikat" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    unitConfig.Description = "Container musikat generated by compose2nix.";
    after = [
      "podman-network-musikat_music-network.service"
      "podman-build-musikat.service"
    ];
    requires = [
      "podman-network-musikat_music-network.service"
      "podman-build-musikat.service"
    ];
    partOf = [
      "podman-compose-musikat-root.target"
    ];
    wantedBy = [
      "podman-compose-musikat-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-musikat_music-network" = {
    unitConfig.Description = "Network musikat_music-network generated by compose2nix.";
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f musikat_music-network";
    };
    script = ''
      podman network inspect musikat_music-network || podman network create musikat_music-network --driver=bridge
    '';
    partOf = [ "podman-compose-musikat-root.target" ];
    wantedBy = [ "podman-compose-musikat-root.target" ];
  };

  # Builds
  systemd.services."podman-build-musikat" = {
    unitConfig.Description = "Build for musikat generated by compose2nix.";
    path = [
      pkgs.podman
      pkgs.git
    ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/nyx/musikat
      podman build -t compose2nix/musikat:latest .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-musikat-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
